package cmpe.sjsu.edu.parser;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

public class StringReader {
	static StringParser parseStringObject=new StringParser();
	BufferedReader br;
	FileReader taggerOutputFile;
	public List<TaggedWordsBucket> readFile(String parserOutPutFile)
	{
		
		List<TaggedWordsBucket> completeList = new ArrayList<TaggedWordsBucket>();
		try {
			/* This part of code is used to open the output file generated by tagger */
			
		 taggerOutputFile = new FileReader(parserOutPutFile);
			 br = new BufferedReader(taggerOutputFile);
			String record = new String();
                        record= br.readLine();
                       
			while(br.ready() && record != null)
			{
				/* A new line is stored in the String now we seperate positive words  */
				
				/* Before sending it to the parse we first verify if its a single sentence 
				 * or a multiple sentenece */
				System.out.println("record::"+record);
				completeList = parseStringObject.parseString(record,completeList);
                record= br.readLine();
            
			}
			
		} catch (Exception e) {
		    /* We catch all the exception here */
			e.printStackTrace();
		} 
		finally{
			try
			{
			br.close();
			}
			catch(Exception ews)
			{
				ews.printStackTrace();
			}
		}
		return completeList;
	}


}
